routes/web.php
<?php

use App\Http\Controllers\ConfigController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FileDownloadController;
use App\Http\Controllers\HumanResourceController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\JenisJenjangController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProfilInstansiController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\SarprasController;
use App\Http\Controllers\SDMController;
use App\Http\Controllers\Section4Controller;
use App\Http\Controllers\SlideshowController;
use App\Http\Controllers\TestimoniController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebsiteController;
use App\Models\Testimoni;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Login & Logout
Route::get('/login', [LoginController::class, 'index'])
    ->name('login')
    ->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::get('/sejarah', [ProfilInstansiController::class, 'sejarah']);
Route::get('/visi-misi', [ProfilInstansiController::class, 'visi_misi']);
Route::get('/tugas-fungsi', [ProfilInstansiController::class, 'tugas_fungsi']);
Route::get('/struktur-organisasi', [ProfilInstansiController::class, 'struktur_organisasi']);
Route::get('/sumber-daya-manusia', [ProfilInstansiController::class, 'sumber_daya_manusia']);
Route::get('/maklumat-layanan', [ProfilInstansiController::class, 'maklumat_layanan']);
Route::get('/faq-anri', [FaqController::class, 'website']);

Route::get('/', [Section4Controller::class, 'section']);

// Beranda Website
Route::get('/', [WebsiteController::class, 'website_beranda']);
Route::get('/kontak-kami', [WebsiteController::class, 'website_kontak']);

// Program Diklat
Route::get('/program-diklat-anri', [WebsiteController::class, 'program_diklat']);

// Detail Program Diklat
Route::get('/detail-program-diklat/{Program:kode_diklat}', [WebsiteController::class, 'program_detail']);

// Kalender
Route::get('/kalender-diklat', [WebsiteController::class, 'kalender']);

// Artikel
Route::get('/artikel', [WebsiteController::class, 'artikel']);

// Berita
Route::get('/berita', [WebsiteController::class, 'berita']);

// Infografis
Route::get('/infografis', [WebsiteController::class, 'infografis']);

// Pengumuman
Route::get('/pengumuman', [WebsiteController::class, 'pengumuman']);

// Sarana Prasarana Frontend
Route::get('/prasarana-sarana', [WebsiteController::class, 'website_sarpras']);

// Menu
Route::get('/ANRI/{Pages:nama_menu}', [WebsiteController::class, 'view_menu']);

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    // dashboard
    Route::get('/dashboard', function () {
        return view('admin.dashboard.dashboard_home');
    });

    // Manajemen User
    Route::resource('/manajemen-user', UserController::class);

    // Jenis dan Jenjang
    Route::delete('/delete-jenis/{Jenis:id}', [JenisJenjangController::class, 'destroy_jenis'])->name('delete-jenis');
    Route::delete('/delete-jenjang/{Jenjang:id}', [JenisJenjangController::class, 'destroy_jenjang'])->name('delete-jenjang');

    // Jenjang dan Jenis
    Route::get('/create-jenis', [JenisJenjangController::class, 'create_jenis'])->name('create-jenis');
    Route::post('/create-jenis', [JenisJenjangController::class, 'store_jenis'])->name('store-jenis');
    Route::get('/update-jenis/{Jenis:id}/edit', [JenisJenjangController::class, 'edit_jenis'])->name('update-jenis');
    Route::put('/update-jenis/{Jenis:id}', [JenisJenjangController::class, 'update_jenis'])->name('update-jenis');
    Route::get('/create-jenjang', [JenisJenjangController::class, 'create_jenjang'])->name('create-jenjang');
    Route::post('/create-jenjang', [JenisJenjangController::class, 'store_jenjang'])->name('store-jenjang');
    Route::get('/update-jenjang/{Jenjang:id}/edit', [JenisJenjangController::class, 'edit_jenjang'])->name('update-jenjang');
    Route::put('/update-jenjang/{Jenjang:id}', [JenisJenjangController::class, 'update_jenjang'])->name('update-jenjang');

    // Program dan Jenis Jenjang
    Route::resource('/program-diklat', ProgramController::class);
    Route::resource('/jenis-jenjang', JenisJenjangController::class);

    // Profil Instansi
    Route::resource('/profil-instansi', ProfilInstansiController::class);

    // Profil Pejabat - SDM
    Route::resource('/profil-pejabat/SDM', HumanResourceController::class);
    Route::resource('/profil-pejabat/jabatan', JabatanController::class);

    // Publikasi File
    Route::resource('/publikasi', PublicationController::class);
    Route::resource('/publikasi-file', FileDownloadController::class);

    // Sarana Prasarana
    Route::resource('/sarana-prasarana', SarprasController::class);

    // Layanan
    Route::resource('/layanan', LayananController::class);

    // Slideshow
    Route::resource('/slideshow', SlideshowController::class);

    // FAQ
    Route::resource('/faq', FaqController::class);

    // Testimoni
    Route::resource('/testimoni', TestimoniController::class);

    // Konfigurasi Situs dan Section
    Route::resource('/konfigurasi-situs', WebsiteController::class);
    Route::resource('/konfigurasi-section', Section4Controller::class);

    // Rubah Password dari sidebar dan navbar
    Route::get('/ubah-password', [UserController::class, 'changePassword'])->name('change-password');
    Route::post('/ubah-password', [UserController::class, 'updatePassword'])->name('update-password');

    // Pages
    Route::resource('/pages', PagesController::class);


});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.dashboard.user.manajemen_user', [
            'total_user' => User::count(),
            'user' => User::oldest()->paginate(3)->withquerystring()
        ]);
    }

    public function changePassword()
    {
        return view('admin.dashboard.password.change_password');
    }

    public function updatePassword(Request $request)
    {
        # Validation
        $request->validate([
            'password_lama' => 'required|min:8|max:10',
            'password_baru' => 'required|min:8|max:10',
        ]);


        #Match The Old Password
        if (!Hash::check($request->password_lama, auth()->user()->password)) {
            return back()->with("error", "Password lama tidak cocok!");
        }


        #Update the new Password
        User::whereId(auth()->user()->id)->update([
            'password' => Hash::make($request->password_baru)
        ]);

        return redirect()->back()->with("success", "Password berhasil di update!");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data_user = User::all();
        return view('admin.dashboard.user.manajemen_user_add
        ', compact('data_user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validateData = $request->validate([
            'name' => 'required',
            'username' => 'required|min:3|max:50',
            'role' => 'required',
            'password' => 'required|min:8|max:10',
        ]);

        // dd('Registrasi Berhasil');  

        $validateData['password'] = bcrypt($validateData['password']);

        User::create($validateData);

        return redirect('/manajemen-user')->with('success', 'User berhasil di tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data_user = User::find($id);
        return view('admin.dashboard.user.manajemen_user_form
        ', compact('data_user', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required',
            'role' => 'required',

        ]);

        $user = User::find($id);

        $user->name = $request->name;
        $user->username = $request->username;
        $user->role = $request->role;
        $user->save();

        $request->session()->flash('success', 'Update berhasil !');

        return redirect('/manajemen-user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        $user->delete()->flash('success', 'Delete berhasil !');

        return redirect('/manajemen-user');
    }
}

resources/views/admin/dashboard/user/manajemen_user.blade.php
@extends('admin.main')

@section('content')
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none">
            <div class="row align-items-center">
                <div class="col-auto">
                    <h2 class="page-title">
                        Manajemen User
                    </h2>
                </div>
                <div class="col-auto d-print-none">
                    <div class="btn-list">
                        <a href="/manajemen-user/create" class="btn btn-primary d-inline-block">
                            <i class="fa fa-plus me-2"></i> Tambah User
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row justify-content-between align-items-center mb-3">
                <div class="col mb-3 mb-md-0 ">
                    <a href="#">Semua ({{ $total_user }})</a>
                    <div class="vr mx-1"></div>
                    <a href="#">Aktif (2)</a>
                    <div class="vr mx-1"></div>
                    <a href="#">Tidak Aktif (1)</a>
                </div>
                <div class="col-auto">
                    <div class="row gx-1">
                        <div class="col-auto">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search...">
                                <div class="input-group-append">
                                    <button class="btn btn-white btn-icon">Cari</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-between align-items-center mb-3">
                <div class="col-auto mb-3 mb-md-0">
                    <div class="row gx-1">
                        <div class="col">
                            <select name="" id="" class="form-control">
                                <option>Bulk Action</option>
                                <option>Set as Aktif</option>
                                <option>Set as Tidak Aktif</option>
                                <option>Move to Trash</option>
                            </select>
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-white">Apply</button>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="row gx-2 align-items-center">
                        {{-- <div class="col-auto">{{ $total_user }} User</div> --}}
                        <div class="col-auto">
                            {{ $user->links() }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="table-responsive">
                    @if (session('success'))
                            <div class="alert alert-success d-flex align-items-center" role="alert">
                                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img"
                                    aria-label="Danger:">
                                    <use xlink:href="#exclamation-triangle-fill" />
                                </svg>
                                <div class="text-center">
                                    {{ session('success') }}
                                </div>
                            </div>
                        @endif
                    <table class="table card-table table-post">
                        <thead>
                            <tr>
                                <th width="10"><input type="checkbox" class="checkall"></th>
                                <th>Username</th>
                                <th>Nama</th>
                                <th>Role</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($user as $users)
                                <tr>
                                    <td><input type="checkbox"></td>
                                    <td>
                                        <a href="/manajemen-user-form" class="font-weight-bold">
                                            {{ $users->username }}
                                        </a>
                                        <div class="action text-muted">
                                            <a href="/manajemen-user/{{ $users->id }}/edit">Edit</a>
                                        </div>
                                    </td>
                                    <td>{{ $users->name }}</td>
                                    <td>{{ $users->role }}</td>
                                    <td>
                                        <div class="badge bg-success">Aktif</div>
                                    </td>
                                </tr>
                            @endforeach

                            {{-- <tr>
                                <td><input type="checkbox"></td>
                                <td>
                                    <a href="/manajemen-user-form" class="font-weight-bold">
                                        Operator
                                    </a>
                                    <div class="action text-muted">
                                        <a href="/manajemen-user-form">Edit</a>
                                        <div class="vr mx-1"></div>
                                        <a href="#">Block</a>
                                        <div class="vr mx-1"></div>
                                        <a href="#" class="text-danger btn-delete">Trash</a>
                                    </div>
                                </td>
                                <td>Operator</td>
                                <td>Operator</td>
                                <td>
                                    <div class="badge bg-secondary">Tidak Aktif</div>
                                </td>
                            </tr> --}}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row justify-content-between align-items-center mt-3">
                <div class="col-auto mb-3 mb-md-0">
                    <div class="row gx-1">
                        <div class="col">
                            <select name="" id="" class="form-control">
                                <option>Bulk Action</option>
                                <option>Set as Aktif</option>
                                <option>Set as Tidak Aktif</option>
                                <option>Move to Trash</option>
                            </select>
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-white">Apply</button>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="row gx-2 align-items-center">
                        <div class="col-auto">{{ $total_user }} User</div>
                        <div class="col-auto">
                            <button class="btn btn-icon btn-white" disabled>
                                <!-- Download SVG icon from http://tabler-icons.io/i/chevrons-left -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <polyline points="11 7 6 12 11 17" />
                                    <polyline points="17 7 12 12 17 17" />
                                </svg>
                            </button>
                            <button class="btn btn-icon btn-white" disabled>
                                <!-- Download SVG icon from http://tabler-icons.io/i/chevron-left -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <polyline points="15 6 9 12 15 18" />
                                </svg>
                            </button>
                            <button class="btn btn-white">1</button>
                            <span>of 3</span>
                            <button class="btn btn-icon btn-white">
                                <!-- Download SVG icon from http://tabler-icons.io/i/chevron-right -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <polyline points="9 6 15 12 9 18" />
                                </svg>
                            </button>
                            <button class="btn btn-icon btn-white">
                                <!-- Download SVG icon from http://tabler-icons.io/i/chevrons-right -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <polyline points="7 7 12 12 7 17" />
                                    <polyline points="13 7 18 12 13 17" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(function() {
            $('#navbar-menu > .navbar-nav > .nav-item > .nav-link > .nav-link-title:contains("Manajemen User")')
                .parents('.nav-item').addClass('active');
        });
    </script>
    <link rel="stylesheet" type="text/css"
        href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $('.btn-delete').on('click', function() {
                Swal.fire({
                    title: 'Hapus Data?',
                    text: "Apakah anda yakin?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya',
                    reverseButtons: true
                }).then((result) => {
                    if (result.isConfirmed) {
                        Swal.fire(
                            'Success!',
                            'Data Berhasil dihapus',
                            'success'
                        )
                    }
                })
            });
        });
    </script>
@endsection

resources/views/admin/dashboard/user/manajemen_user_add.blade.php
@extends('admin.main')

@section('content')
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none">
            <div class="row align-items-center">
                <div class="col-auto">
                    <h2 class="page-title">
                        Tambah User
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row">
                <div class="col-md-8 mb-4 mb-md-0">
                    <form action="{{ route('manajemen-user.store') }}" method="POST">
                        @csrf
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="mb-3">
                                    <div class="form-label">Username</div>
                                    <input type="text" id="username" name="username"
                                        class="form-control @error('username') is-invalid @enderror" required
                                        value="{{ old('username') }}">
                                    @error('username')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Nama</div>
                                    <input type="text" id="name" name="name"
                                        class="form-control @error('name') is-invalid @enderror" required
                                        value="{{ old('name') }}">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Role</div>
                                    <select id="role" name="role"
                                        class="form-control @error('role') is-invalid @enderror" required>
                                        <option value="admin">Admin</option>
                                        <option value="operator">Operator</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Status</div>
                                    <select name="" id="" class="form-control">
                                        <option value="">Aktif</option>
                                        <option value="">Tidak Aktif</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Password</div>
                                    <input type="text" id="password" name="password"
                                        class="form-control @error('password') is-invalid @enderror" required>
                                    @error('password')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(function() {
            $('#navbar-menu > .navbar-nav > .nav-item > .nav-link > .nav-link-title:contains("Manajemen User")')
                .parents('.nav-item').addClass('active');
        });
    </script>
@endsection

resources/views/admin/dashboard/user/manajemen_user_form.blade.php
@extends('admin.main')

@section('content')
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none">
            <div class="row align-items-center">
                <div class="col-auto">
                    <h2 class="page-title">
                        Manajemen User
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row">
                <div class="col-md-8 mb-4 mb-md-0">
                    <form action="/manajemen-user/{{ $data_user->id }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="mb-3">
                                    <div class="form-label">Username</div>
                                    <input type="text" id="username" name="username" class="form-control"
                                        value="{{ $data_user->username }}">
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Nama</div>
                                    <input type="text" id="name" name="name" class="form-control"
                                        value="{{ $data_user->name }}">
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Role</div>
                                    <select id="role" name="role" class="form-control">
                                        <option value="admin">Admin</option>
                                        <option value="operator">Operator</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Status</div>
                                    <select name="" id="" class="form-control">
                                        <option value="">Aktif</option>
                                        <option value="">Tidak Aktif</option>
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(function() {
            $('#navbar-menu > .navbar-nav > .nav-item > .nav-link > .nav-link-title:contains("Manajemen User")')
                .parents('.nav-item').addClass('active');
        });
    </script>
@endsection